from flask import Blueprint, render_template, request, jsonify, send_file
from app.services import calculate_bmi

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io
from typing import Dict, List

main = Blueprint("main", __name__)

# In-memory storage
bmi_history: List[Dict] = []
last_bmi_result: Dict = {}


@main.route("/")
def index() -> str:
    return render_template(
        "index.html",
        bmi=None,
        category=None,
        color=None,
        recommendation=None,
        indicator_position=0,
        error=None
    )


@main.route("/calculate", methods=["POST"])
def calculate() -> str:
    try:
        weight = float(request.form["weight"])
        height = float(request.form["height"])
        unit = request.form.get("unit", "metric")

        if weight <= 0 or height <= 0:
            raise ValueError

        # Convert imperial → metric
        if unit == "imperial":
            weight *= 0.453592
            height *= 0.0254

        # Convert cm → m if needed
        if height > 3:
            height /= 100

        bmi, category, color, recommendation = calculate_bmi(weight, height)

        global last_bmi_result
        last_bmi_result = {
            "bmi": bmi,
            "category": category,
            "recommendation": recommendation
        }

        bmi_history.append({
            "weight": round(weight, 2),
            "height": round(height, 2),
            "bmi": bmi,
            "category": category
        })

        # Indicator position for UI (10–40 BMI scale)
        scale_bmi = max(10, min(bmi, 40))
        indicator_position = ((scale_bmi - 10) / 30) * 100

        return render_template(
            "index.html",
            bmi=bmi,
            category=category,
            color=color,
            recommendation=recommendation,
            indicator_position=indicator_position,
            error=None
        )

    except ValueError:
        return render_template(
            "index.html",
            bmi=None,
            category=None,
            color=None,
            recommendation=None,
            indicator_position=0,
            error="Please enter valid positive numbers for weight and height."
        )


@main.route("/api/bmi", methods=["POST"])
def bmi_api():
    data = request.get_json()

    weight = float(data["weight"])
    height = float(data["height"])

    if height > 3:
        height /= 100

    bmi, category, color, recommendation = calculate_bmi(weight, height)

    return jsonify({
        "bmi": bmi,
        "category": category,
        "color": color,
        "recommendation": recommendation
    })


@main.route("/history")
def history():
    return render_template("history.html", history=bmi_history)


@main.route("/download-pdf")
def download_pdf():
    if not last_bmi_result:
        return "No BMI data available to generate PDF."

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(200, 750, "BMI REPORT")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(100, 710, f"BMI Value: {last_bmi_result['bmi']}")
    pdf.drawString(100, 690, f"Category: {last_bmi_result['category']}")

    pdf.drawString(100, 650, "Health Recommendation:")
    pdf.drawString(120, 630, last_bmi_result["recommendation"])

    pdf.drawString(100, 580, "Generated by BMI Calculator Web App")

    pdf.showPage()
    pdf.save()
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="bmi_report.pdf",
        mimetype="application/pdf"
    )
